name: Build Android APK and AAB

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'zulu'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          libncurses5-dev \
          libncursesw5-dev \
          libreadline-dev \
          libssl-dev \
          zlib1g-dev \
          libbz2-dev \
          libsqlite3-dev \
          python3-dev \
          python3-pip \
          libffi-dev \
          git \
          unzip

    - name: Set up Android SDK
      run: |
        wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip -d android-sdk
        mkdir -p android-sdk/cmdline-tools/latest
        mv android-sdk/cmdline-tools/* android-sdk/cmdline-tools/latest/
        export ANDROID_SDK_ROOT=$(pwd)/android-sdk
        echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
        yes | android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT "build-tools;36.0.0" "platforms;android-34" "ndk;25.2.9519653" "platform-tools"

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Install Python dependencies
      run: |
        uv sync
        . .venv/bin/activate

    - name: Initialize Buildozer spec
      run: |
        . .venv/bin/activate
        buildozer init
        # Modify buildozer.spec to include permissions and requirements
        sed -i 's/requirements = /requirements = kivy==2.3.1,pyjnius==1.6.1,pyserial==3.5,/' buildozer.spec
        sed -i 's/#android.permissions = /android.permissions = BLUETOOTH,BLUETOOTH_ADMIN,BLUETOOTH_CONNECT,BLUETOOTH_SCAN,ACCESS_FINE_LOCATION,/' buildozer.spec
        sed -i 's/title = /title = RobotControl/' buildozer.spec
        sed -i 's/package.name = /package.name = robotcontrol/' buildozer.spec

    - name: Build APK and AAB with Buildozer
      run: |
        . .venv/bin/activate
        buildozer android debug
        buildozer android release aab

    - name: Upload APK and AAB
      uses: actions/upload-artifact@v4
      with:
        name: android-apk-aab
        path: bin/*.{apk,aab}